# Generated by Django 6.0.2 on 2026-03-12 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("RFI_ASSIGNED", "RFI Assigned"),
                            ("RFI_ANSWERED", "RFI Answered"),
                            ("CO_PENDING", "Change Order Pending"),
                            ("CO_APPROVED", "Change Order Approved"),
                            ("MAINTENANCE_LOGGED", "Maintenance Logged"),
                            ("GENERAL_UPDATE", "General Update"),
                        ],
                        default="GENERAL_UPDATE",
                        max_length=50,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
