# Generated by Django 6.0.2 on 2026-03-16 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notification_action_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        message="action_url must be a valid relative path starting with '/'",
                        regex="^\\/[a-zA-Z0-9\\-\\/\\?\\=\\&\\.\\_\\#\\%]*$",
                    )
                ],
            ),
        ),
    ]
