# Generated by Django 6.0.2 on 2026-03-30 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_alter_notification_action_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        message="action_url must be a valid relative path starting with '/' and must not contain traversal characters",
                        regex="^\\/(?!.*(?:\\.\\.|//))[a-zA-Z0-9\\-\\/\\?\\=\\&\\.\\_\\#\\%]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("RFI_ASSIGNED", "RFI Assigned"),
                    ("RFI_ANSWERED", "RFI Answered"),
                    ("CO_PENDING", "Change Order Pending"),
                    ("CO_APPROVED", "Change Order Approved"),
                    ("MAINTENANCE_LOGGED", "Maintenance Logged"),
                    ("GENERAL_UPDATE", "General Update"),
                    ("SYSTEM_ALERT", "System Alert"),
                ],
                default="GENERAL_UPDATE",
                max_length=50,
            ),
        ),
    ]
