# Generated by Django 6.0.2 on 2026-03-07 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("ACTIVE", "Active"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                (
                    "budget_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "budget_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "completion_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("MEMBER_ADDED", "Member Added"),
                            ("MEMBER_REMOVED", "Member Removed"),
                            ("DOCUMENT_UPLOADED", "Document Uploaded"),
                            ("PHOTO_UPLOADED", "Photo Uploaded"),
                            ("RFI_CREATED", "RFI Created"),
                            ("RFI_RESOLVED", "RFI Resolved"),
                            ("CO_CREATED", "Change Order Created"),
                            ("CO_APPROVED", "Change Order Approved"),
                            ("CO_REJECTED", "Change Order Rejected"),
                            ("MILESTONE_APPROVED", "Milestone Approved"),
                            ("COST_UPDATED", "Cost Updated"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "event_type", "created_at"],
                        name="project_eve_project_a25e1c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CLIENT", "Client"),
                            ("AGENT", "Agent"),
                            ("SITE_OFFICER", "Site Officer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_members",
                "unique_together": {("project", "user")},
            },
        ),
    ]
