# Generated by Django 6.0.2 on 2026-03-13 18:49

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_milestone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="budget_spent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="budget_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="completion_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "Planning"),
                    ("ACTIVE", "Active"),
                    ("ON_HOLD", "On Hold"),
                    ("COMPLETED", "Completed"),
                    ("ARCHIVED", "Archived"),
                ],
                db_index=True,
                default="PLANNING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("CLIENT", "Client"),
                    ("AGENT", "Agent"),
                    ("SITE_OFFICER", "Site Officer"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["project", "status"], name="milestones_project_f51c6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["approval_token"], name="milestones_approva_bb4c4a_idx"
            ),
        ),
    ]
