# Generated by Django 6.0.2 on 2026-03-16 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_budget_spent_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="milestone",
            name="milestones_approva_bb4c4a_idx",
        ),
    ]
