# Generated by Django 6.0.2 on 2026-03-28 14:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_remove_milestone_milestones_approva_bb4c4a_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("UPDATED", "Updated"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("MEMBER_ADDED", "Member Added"),
                    ("MEMBER_REMOVED", "Member Removed"),
                    ("DOCUMENT_UPLOADED", "Document Uploaded"),
                    ("PHOTO_UPLOADED", "Photo Uploaded"),
                    ("RFI_CREATED", "RFI Created"),
                    ("RFI_RESOLVED", "RFI Resolved"),
                    ("CO_CREATED", "Change Order Created"),
                    ("CO_APPROVED", "Change Order Approved"),
                    ("CO_REJECTED", "Change Order Rejected"),
                    ("MILESTONE_APPROVED", "Milestone Approved"),
                    ("COST_UPDATED", "Cost Updated"),
                    ("EXPENSE_SUBMITTED", "Expense Submitted"),
                    ("EXPENSE_APPROVED", "Expense Approved"),
                    ("EXPENSE_REJECTED", "Expense Rejected"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATERIALS", "Materials & Supplies"),
                            ("LABOR", "Labor & Wages"),
                            ("EQUIPMENT", "Equipment Rental"),
                            ("SUBCONTRACTOR", "Subcontractor Payment"),
                            ("PERMITS", "Permits & Fees"),
                            ("TRANSPORTATION", "Transportation & Logistics"),
                            ("UTILITIES", "Site Utilities"),
                            ("SAFETY", "Safety & Compliance"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("expense_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="projects.project",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "expenses",
                "ordering": ["-expense_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"], name="expenses_project_93d396_idx"
                    ),
                    models.Index(
                        fields=["project", "category"],
                        name="expenses_project_4a14fb_idx",
                    ),
                    models.Index(
                        fields=["created_by", "status"],
                        name="expenses_created_31ff14_idx",
                    ),
                ],
            },
        ),
    ]
