# Generated by Django 6.0.2 on 2026-03-28 15:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_expense_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATERIALS", "Materials & Supplies"),
                            ("LABOR", "Labor & Wages"),
                            ("EQUIPMENT", "Equipment Rental"),
                            ("SUBCONTRACTOR", "Subcontractor Payment"),
                            ("PERMITS", "Permits & Fees"),
                            ("TRANSPORTATION", "Transportation & Logistics"),
                            ("UTILITIES", "Site Utilities"),
                            ("SAFETY", "Safety & Compliance"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned cost for this work item (Planned Value in EVM terms)",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual expenditure after completion",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "cost_variance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="estimated_cost - actual_cost. Negative = overrun.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Budget Requested"),
                            ("APPROVED", "Budget Approved"),
                            ("REJECTED", "Budget Rejected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RECONCILING", "Reconciling Actual Cost"),
                            ("COMPLETED", "Completed"),
                            ("OVERRUN_PENDING", "Overrun — Awaiting Client Consent"),
                            ("OVERRUN_APPROVED", "Overrun Approved by Client"),
                            ("OVERRUN_REJECTED", "Overrun Rejected by Client"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("budget_approved_at", models.DateTimeField(blank=True, null=True)),
                ("budget_rejection_reason", models.TextField(blank=True, default="")),
                (
                    "overrun_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount exceeding the original estimate (actual - estimated)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "overrun_justification",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why did the actual cost exceed the estimate?",
                    ),
                ),
                ("overrun_consent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "overrun_consent_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Cryptographic token for client overrun consent",
                        unique=True,
                    ),
                ),
                ("overrun_rejection_reason", models.TextField(blank=True, default="")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Relative weight for project completion calculation",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_budget_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_budget_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "overrun_consent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overrun_consent_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_requests",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "budget_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="budget_requ_project_5ff8bb_idx",
                    ),
                    models.Index(
                        fields=["project", "category"],
                        name="budget_requ_project_f89ed5_idx",
                    ),
                    models.Index(
                        fields=["created_by", "status"],
                        name="budget_requ_created_8bad76_idx",
                    ),
                ],
            },
        ),
    ]
