# Generated by Django 6.0.2 on 2026-03-30 06:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_budget_request_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="WBSTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wbs_code", models.CharField(db_index=True, max_length=50)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "global_weight",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                (
                    "local_weight",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                (
                    "rule_of_credit",
                    models.CharField(
                        choices=[
                            ("0/100", "0/100 Rule (Start = 0%, Finish = 100%)"),
                            ("50/50", "50/50 Rule (Start = 50%, Finish = 100%)"),
                            ("20/80", "20/80 Rule (Start = 20%, Finish = 100%)"),
                            ("UNITS", "Units Completed (Quantity-based)"),
                            ("MILESTONE", "Incremental Milestones"),
                        ],
                        default="0/100",
                        max_length=20,
                    ),
                ),
                ("planned_duration_days", models.IntegerField(default=1)),
                ("planned_start_date", models.DateField(blank=True, null=True)),
                ("planned_end_date", models.DateField(blank=True, null=True)),
                ("actual_start_date", models.DateField(blank=True, null=True)),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=15
                    ),
                ),
                (
                    "completed_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=15
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_tasks",
                        to="projects.wbstask",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wbs_tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "wbs_tasks",
                "ordering": ["wbs_code"],
                "unique_together": {("project", "wbs_code")},
            },
        ),
    ]
