# Generated by Django 6.0.2 on 2026-03-30 07:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_wbstask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wbstask",
            name="global_weight",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="wbstask",
            name="local_weight",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=7
            ),
        ),
    ]
