# Generated by Django 6.0.2 on 2026-03-30 09:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_wbstask_global_weight_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EVMBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_at_completion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total authorized budget for EVM calculations (BAC)",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(help_text="Baseline planned start date"),
                ),
                (
                    "planned_end_date",
                    models.DateField(help_text="Baseline planned end date"),
                ),
                (
                    "pv_curve",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Planned Value S-curve: weekly cumulative % targets",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Once locked, the baseline cannot be modified",
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "EVM Baseline",
                "verbose_name_plural": "EVM Baselines",
                "db_table": "evm_baselines",
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Client-generated UUID v4 idempotency key",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(help_text="API endpoint path", max_length=255),
                ),
                (
                    "request_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the request body for debugging",
                        max_length=64,
                    ),
                ),
                (
                    "response_status",
                    models.IntegerField(
                        help_text="HTTP status code of the cached response"
                    ),
                ),
                (
                    "response_body",
                    models.JSONField(help_text="Serialized response data"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Idempotency Record",
                "verbose_name_plural": "Idempotency Records",
                "db_table": "idempotency_records",
            },
        ),
        migrations.RemoveIndex(
            model_name="budgetrequest",
            name="budget_requ_project_5ff8bb_idx",
        ),
        migrations.RemoveIndex(
            model_name="budgetrequest",
            name="budget_requ_project_f89ed5_idx",
        ),
        migrations.RemoveIndex(
            model_name="budgetrequest",
            name="budget_requ_created_8bad76_idx",
        ),
        migrations.AddField(
            model_name="expense",
            name="actual_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Final actual cost submitted after work completion",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="consent_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 hash of the consent metadata for non-repudiation",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="consent_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Full consent context: user, IP, device, timestamp, amounts",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="consented_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when consent was granted", null=True
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="consented_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Client who granted variance consent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consented_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="encumbered_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when funds were encumbered", null=True
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="estimated_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original estimate submitted for budget reservation (encumbrance)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="variance_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="actual_amount - estimated_amount (positive = overrun)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("FUNDS_CHECK", "Funds Check"),
                    ("ENCUMBERED", "Encumbered"),
                    ("RECONCILING", "Reconciling"),
                    ("CONSENT_REQUIRED", "Consent Required"),
                    ("SUBMITTED", "Submitted for Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="evmbaseline",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_baselines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evmbaseline",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evm_baseline",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idempotency_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="budgetrequest",
            name="budget_approved_by",
        ),
        migrations.RemoveField(
            model_name="budgetrequest",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="budgetrequest",
            name="overrun_consent_by",
        ),
        migrations.RemoveField(
            model_name="budgetrequest",
            name="project",
        ),
        migrations.DeleteModel(
            name="WBSTask",
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["key", "user"], name="idempotency_key_16ec05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["created_at"], name="idempotency_created_3fb3ea_idx"
            ),
        ),
        migrations.DeleteModel(
            name="BudgetRequest",
        ),
    ]
