# Generated by Django 6.0.2 on 2026-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_evm_encumbrance_idempotency"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="signature_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 hash binding approval context (user, IP, time)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="signature_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
