# Generated by Django 6.0.2 on 2026-03-31 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_add_rls_policies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="milestone",
            name="signature_hash",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="signature_metadata",
        ),
    ]
