# Generated by Django 6.0.2 on 2026-03-31 11:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_remove_milestone_signature_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("UPDATED", "Updated"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("MEMBER_ADDED", "Member Added"),
                    ("MEMBER_REMOVED", "Member Removed"),
                    ("DOCUMENT_UPLOADED", "Document Uploaded"),
                    ("PHOTO_UPLOADED", "Photo Uploaded"),
                    ("RFI_CREATED", "RFI Created"),
                    ("RFI_RESOLVED", "RFI Resolved"),
                    ("CO_CREATED", "Change Order Created"),
                    ("CO_APPROVED", "Change Order Approved"),
                    ("CO_REJECTED", "Change Order Rejected"),
                    ("MILESTONE_APPROVED", "Milestone Approved"),
                    ("COST_UPDATED", "Cost Updated"),
                    ("EXPENSE_SUBMITTED", "Expense Submitted"),
                    ("EXPENSE_APPROVED", "Expense Approved"),
                    ("EXPENSE_REJECTED", "Expense Rejected"),
                    ("COMPLETION_UPDATED", "Completion Updated"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="CompletionUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Project completion % before this update",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "new_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Project completion % after this update",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "delta_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Computed: new_pct - previous_pct",
                        max_digits=5,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the physical work completed in this increment"
                    ),
                ),
                (
                    "ev_at_update",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Earned Value at the moment of this update (new_pct × BAC)",
                        max_digits=15,
                    ),
                ),
                (
                    "ac_at_update",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Actual Cost at the moment of this update",
                        max_digits=15,
                    ),
                ),
                (
                    "cpi_at_update",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Cost Performance Index at the moment of this update",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_expenses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Expenses associated with this progress increment",
                        related_name="completion_updates",
                        to="projects.expense",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_updates",
                        to="projects.project",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_completion_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "completion_updates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"],
                        name="completion__project_e34998_idx",
                    ),
                    models.Index(
                        fields=["reported_by", "-created_at"],
                        name="completion__reporte_6d9cfe_idx",
                    ),
                ],
            },
        ),
    ]
