# Generated by Django 6.0.2 on 2026-03-31 12:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_completion_update_audit_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Name of the work item", max_length=255),
                ),
                ("description", models.TextField(help_text="Detailed scope of work")),
                (
                    "completion_delta",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="How much % progress this work adds to the project",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Initial cost estimate submitted by Site Officer",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final actual cost reported when work finishes",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "variance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="actual_cost - estimated_cost",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved (Funds Encumbered)"),
                            ("WORK_STARTED", "Work Started"),
                            ("COMPLETED", "Completed and Reconciled"),
                            ("OVERRUN_DETECTED", "Overrun Detected (Consent Required)"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("consent_required", models.BooleanField(default=False)),
                (
                    "consent_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("consent_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_completion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client_consent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consented_completion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_expense",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="originating_completion_request",
                        to="projects.expense",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "completion_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="completion__project_0cb572_idx",
                    ),
                    models.Index(
                        fields=["requested_by"], name="completion__request_8e556f_idx"
                    ),
                ],
            },
        ),
    ]
