# Generated by Django 6.0.2 on 2026-04-02 14:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0017_resource_logs"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dailyprogresssnapshot",
            new_name="daily_progr_project_3d1a39_idx",
            old_name="daily_snap_project_date_idx",
        ),
        migrations.RenameIndex(
            model_name="wbsnode",
            new_name="wbs_nodes_project_b58d06_idx",
            old_name="wbs_nodes_project_parent_idx",
        ),
        migrations.RenameIndex(
            model_name="wbsnode",
            new_name="wbs_nodes_project_b3eaa9_idx",
            old_name="wbs_nodes_leaf_status_idx",
        ),
        migrations.RenameIndex(
            model_name="wbsnode",
            new_name="wbs_nodes_project_a0da0f_idx",
            old_name="wbs_nodes_project_depth_idx",
        ),
        migrations.RenameIndex(
            model_name="wbsprogressentry",
            new_name="wbs_progres_wbs_nod_928d5d_idx",
            old_name="wbs_progress_node_date_idx",
        ),
        migrations.RenameIndex(
            model_name="wbsprogressentry",
            new_name="wbs_progres_reporte_cdd1e1_idx",
            old_name="wbs_progress_reporter_idx",
        ),
        migrations.RenameIndex(
            model_name="wbsprogressentry",
            new_name="wbs_progres_log_dat_52828f_idx",
            old_name="wbs_progress_log_date_idx",
        ),
        migrations.AddField(
            model_name="wbsnode",
            name="actual_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Actual cost encumbered/spent for this WBS node.",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
