# Generated by Django 6.0.2 on 2026-04-11 09:55

from django.db import migrations, models


def drop_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("""
        DROP POLICY IF EXISTS expense_update_policy ON expenses CASCADE;
        DROP POLICY IF EXISTS expense_insert_policy ON expenses CASCADE;
        DROP POLICY IF EXISTS expense_client_visibility ON expenses CASCADE;
        DROP POLICY IF EXISTS expense_member_access ON expenses CASCADE;
        ALTER TABLE expenses DISABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS evm_baseline_write_policy ON evm_baselines CASCADE;
        DROP POLICY IF EXISTS evm_baseline_member_access ON evm_baselines CASCADE;
        ALTER TABLE evm_baselines DISABLE ROW LEVEL SECURITY;
    """)


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0018_rename_daily_snap_project_date_idx_daily_progr_project_3d1a39_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(drop_rls, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="completionrequest",
            name="completion__project_0cb572_idx",
        ),
        migrations.RemoveIndex(
            model_name="completionrequest",
            name="completion__request_8e556f_idx",
        ),
        migrations.RemoveIndex(
            model_name="completionupdate",
            name="completion__project_e34998_idx",
        ),
        migrations.RemoveIndex(
            model_name="completionupdate",
            name="completion__reporte_6d9cfe_idx",
        ),
        migrations.AlterUniqueTogether(
            name="dailyprogresssnapshot",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="dailyprogresssnapshot",
            name="daily_progr_project_3d1a39_idx",
        ),
        migrations.RemoveField(
            model_name="evmbaseline",
            name="locked_by",
        ),
        migrations.RemoveField(
            model_name="evmbaseline",
            name="project",
        ),
        migrations.RemoveIndex(
            model_name="expense",
            name="expenses_project_93d396_idx",
        ),
        migrations.RemoveIndex(
            model_name="expense",
            name="expenses_project_4a14fb_idx",
        ),
        migrations.RemoveIndex(
            model_name="expense",
            name="expenses_created_31ff14_idx",
        ),
        migrations.RemoveField(
            model_name="laborresourcelog",
            name="progress_entry",
        ),
        migrations.RemoveField(
            model_name="machineryresourcelog",
            name="progress_entry",
        ),
        migrations.RemoveField(
            model_name="materialresourcelog",
            name="progress_entry",
        ),
        migrations.AlterUniqueTogether(
            name="wbsnode",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="wbsnode",
            name="wbs_nodes_project_b58d06_idx",
        ),
        migrations.RemoveIndex(
            model_name="wbsnode",
            name="wbs_nodes_project_b3eaa9_idx",
        ),
        migrations.RemoveIndex(
            model_name="wbsnode",
            name="wbs_nodes_project_a0da0f_idx",
        ),
        migrations.RemoveIndex(
            model_name="wbsprogressentry",
            name="wbs_progres_wbs_nod_928d5d_idx",
        ),
        migrations.RemoveIndex(
            model_name="wbsprogressentry",
            name="wbs_progres_reporte_cdd1e1_idx",
        ),
        migrations.RemoveIndex(
            model_name="wbsprogressentry",
            name="wbs_progres_log_dat_52828f_idx",
        ),
        migrations.AlterField(
            model_name="projectevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("UPDATED", "Updated"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("MEMBER_ADDED", "Member Added"),
                    ("MEMBER_REMOVED", "Member Removed"),
                    ("DOCUMENT_UPLOADED", "Document Uploaded"),
                    ("RFI_CREATED", "RFI Created"),
                    ("RFI_ANSWERED", "RFI Answered"),
                    ("CHANGE_ORDER_SUBMITTED", "Change Order Submitted"),
                    ("CHANGE_ORDER_APPROVED", "Change Order Approved"),
                ],
                max_length=30,
            ),
        ),
        migrations.RemoveField(
            model_name="completionrequest",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="completionrequest",
            name="client_consent_by",
        ),
        migrations.RemoveField(
            model_name="completionrequest",
            name="linked_expense",
        ),
        migrations.RemoveField(
            model_name="completionrequest",
            name="project",
        ),
        migrations.RemoveField(
            model_name="completionrequest",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="completionrequest",
            name="wbs_node",
        ),
        migrations.RemoveField(
            model_name="completionupdate",
            name="linked_expenses",
        ),
        migrations.RemoveField(
            model_name="completionupdate",
            name="project",
        ),
        migrations.RemoveField(
            model_name="completionupdate",
            name="reported_by",
        ),
        migrations.RemoveField(
            model_name="dailyprogresssnapshot",
            name="project",
        ),
        migrations.DeleteModel(
            name="EVMBaseline",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="consented_by",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="project",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="wbs_node",
        ),
        migrations.DeleteModel(
            name="LaborResourceLog",
        ),
        migrations.DeleteModel(
            name="MachineryResourceLog",
        ),
        migrations.DeleteModel(
            name="MaterialResourceLog",
        ),
        migrations.RemoveField(
            model_name="wbsnode",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="wbsnode",
            name="project",
        ),
        migrations.RemoveField(
            model_name="wbsprogressentry",
            name="reported_by",
        ),
        migrations.RemoveField(
            model_name="wbsprogressentry",
            name="wbs_node",
        ),
        migrations.DeleteModel(
            name="CompletionRequest",
        ),
        migrations.DeleteModel(
            name="CompletionUpdate",
        ),
        migrations.DeleteModel(
            name="DailyProgressSnapshot",
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="WBSNode",
        ),
        migrations.DeleteModel(
            name="WBSProgressEntry",
        ),
    ]
