# Generated by Django 6.0.2 on 2026-04-11 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0019_remove_completionrequest_completion__project_0cb572_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectevent",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("UPDATED", "Updated"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("MEMBER_ADDED", "Member Added"),
                    ("MEMBER_REMOVED", "Member Removed"),
                    ("DOCUMENT_UPLOADED", "Document Uploaded"),
                    ("RFI_CREATED", "RFI Created"),
                    ("RFI_ANSWERED", "RFI Answered"),
                    ("CHANGE_ORDER_SUBMITTED", "Change Order Submitted"),
                    ("CHANGE_ORDER_APPROVED", "Change Order Approved"),
                    ("CO_REJECTED", "Change Order Rejected"),
                    ("PHOTO_UPLOADED", "Photo Uploaded"),
                    ("MILESTONE_APPROVED", "Milestone Approved"),
                ],
                max_length=30,
            ),
        ),
    ]
