# Generated by Django 6.0.2 on 2026-04-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0020_fix_event_types_and_actor_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="is_frozen",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Temporarily suspend member access without permanent removal.",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "Planning"),
                    ("ACTIVE", "Active"),
                    ("ON_HOLD", "On Hold"),
                    ("COMPLETED", "Completed"),
                    ("ARCHIVED", "Archived"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                ],
                db_index=True,
                default="PLANNING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("UPDATED", "Updated"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("MEMBER_ADDED", "Member Added"),
                    ("MEMBER_REMOVED", "Member Removed"),
                    ("MEMBER_FROZEN", "Member Frozen"),
                    ("MEMBER_UNFROZEN", "Member Unfrozen"),
                    ("DOCUMENT_UPLOADED", "Document Uploaded"),
                    ("RFI_CREATED", "RFI Created"),
                    ("RFI_ANSWERED", "RFI Answered"),
                    ("CHANGE_ORDER_SUBMITTED", "Change Order Submitted"),
                    ("CHANGE_ORDER_APPROVED", "Change Order Approved"),
                    ("CO_REJECTED", "Change Order Rejected"),
                    ("PHOTO_UPLOADED", "Photo Uploaded"),
                    ("MILESTONE_APPROVED", "Milestone Approved"),
                ],
                max_length=30,
            ),
        ),
    ]
