# Generated by Django 6.0.2 on 2026-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfi",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("PENDING_RESPONSE", "Pending Response"),
                    ("ANSWERED", "Answered"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
