import io
import uuid
import logging
from celery import shared_task
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

from .models import ChangeOrder

from documents.models import Document

from notifications.services import notify_and_email

logger = logging.getLogger(__name__)


@shared_task
def generate_co_pdf(co_id):
    try:
        co = ChangeOrder.objects.get(id=co_id)
    except ChangeOrder.DoesNotExist:
        logger.error(f"ChangeOrder {co_id} not found.")
        return f"ChangeOrder {co_id} missing."

    try:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch
        )
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Title"],
            fontSize=18,
            spaceAfter=12,
        )
        heading_style = ParagraphStyle(
            "CustomHeading",
            parent=styles["Heading2"],
            fontSize=14,
            spaceAfter=6,
            textColor=colors.HexColor("#1a365d"),
        )

        elements = []

        elements.append(Paragraph("ConstructIQ — Change Order", title_style))
        elements.append(Spacer(1, 12))

        meta_data = [
            ["Project:", co.project.name],
            ["CO Title:", co.title],
            ["Status:", co.status],
            ["Reason Code:", co.reason_code or "N/A"],
            ["Cost Impact:", f"${co.cost_impact:,.2f}"],
            ["Schedule Impact:", f"{co.schedule_impact_days} days"],
        ]

        meta_table = Table(meta_data, colWidths=[1.5 * inch, 4.5 * inch])
        meta_table.setStyle(
            TableStyle(
                [
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 11),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f4f8")),
                ]
            )
        )
        elements.append(meta_table)
        elements.append(Spacer(1, 24))

        elements.append(Paragraph("Scope of Changes", heading_style))
        elements.append(Spacer(1, 6))
        desc_text = (
            co.description.replace("\n", "<br/>")
            if co.description
            else "No description provided."
        )
        elements.append(Paragraph(desc_text, styles["Normal"]))
        elements.append(Spacer(1, 24))

        elements.append(Paragraph("Approvals", heading_style))
        elements.append(Spacer(1, 6))

        sig_data = [
            ["Submitted By:", co.created_by.email],
            ["Approved By:", co.approved_by.email if co.approved_by else "Pending"],
            [
                "Digital Signature Hash:",
                co.signature_hash if co.signature_hash else "Pending",
            ],
        ]
        sig_table = Table(sig_data, colWidths=[2.0 * inch, 4.0 * inch])
        sig_table.setStyle(
            TableStyle(
                [
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        elements.append(sig_table)
        elements.append(Spacer(1, 24))

        elements.append(
            Paragraph(
                f"Generated by ConstructIQ on {co.updated_at.strftime('%Y-%m-%d %H:%M UTC')}",
                ParagraphStyle(
                    "Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey
                ),
            )
        )

        doc.build(elements)
        buffer.seek(0)

        pdf_key = f"projects/{co.project.id}/change-orders/CO_{co.id}_{uuid.uuid4().hex[:8]}.pdf"
        saved_pdf_path = default_storage.save(pdf_key, ContentFile(buffer.read()))

        co.pdf_s3_key = saved_pdf_path
        co.save(update_fields=["pdf_s3_key"])

        doc_record = Document.objects.create(
            project=co.project,
            uploaded_by=co.created_by,
            title=f"Change Order #{co.id} - {co.title}",
            file_type="PDF",
            s3_key=saved_pdf_path,
            is_current=True,
        )

        notify_and_email(
            recipient=co.created_by,
            notification_type="SYSTEM_ALERT",
            message=f"The PDF for Change Order '{co.title}' is ready.",
            action_url=f"/projects/{co.project.id}/documents/{doc_record.id}",
        )

        return f"Successfully generated PDF for CO {co_id}."

    except Exception as e:
        logger.error(f"Failed to generate PDF for CO {co_id}: {str(e)}")
        return f"Error building PDF: {str(e)}"
