# Generated by Django 6.0.2 on 2026-03-13 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("change_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changeorder",
            name="approval_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="changeorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
