# Generated by Django 6.0.2 on 2026-03-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("change_orders", "0002_alter_changeorder_approval_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeorder",
            name="pdf_s3_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
