# Generated by Django 6.0.2 on 2026-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("change_orders", "0003_changeorder_pdf_s3_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeorder",
            name="signature_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
