# Generated by Django 6.0.2 on 2026-03-31 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("change_orders", "0004_changeorder_signature_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changeorder",
            name="signature_metadata",
        ),
    ]
