# Generated by Django 6.0.2 on 2026-03-10 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0002_milestone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("version", models.PositiveIntegerField(default=1)),
                ("s3_key", models.CharField(blank=True, default="", max_length=500)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("DWG", "AutoCAD Drawing"),
                            ("IFC", "IFC (BIM)"),
                            ("DOCX", "Word Document"),
                            ("XLSX", "Excel Spreadsheet"),
                            ("IMAGE", "Image"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-version"],
            },
        ),
    ]
