# Generated by Django 6.0.2 on 2026-03-13 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("projects", "0003_alter_project_budget_spent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={},
        ),
        migrations.AlterField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["project", "title", "-version"],
                name="documents_project_6469c9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("project", "title", "version"), name="unique_document_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("project", "title"),
                name="unique_current_document",
            ),
        ),
    ]
