# Generated by Django 6.0.2 on 2026-03-27 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("change_orders", "0003_changeorder_pdf_s3_key"),
        ("projects", "0004_remove_milestone_milestones_approva_bb4c4a_idx"),
        ("rfi", "0002_alter_rfi_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BIMProjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Main Structural Model", max_length=255),
                ),
                (
                    "model_file",
                    models.FileField(
                        help_text="Upload GLB or GLTF for the browser viewer.",
                        upload_to="bim/models/",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "scene_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Scene environment settings (exposure, background, ground plane).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bim_models",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "BIM Model",
                "db_table": "bim_models",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="BIMHotspot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("pos_x", models.FloatField(default=0.0)),
                ("pos_y", models.FloatField(default=0.0)),
                ("pos_z", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bim_hotspots",
                        to="change_orders.changeorder",
                    ),
                ),
                (
                    "rfi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bim_hotspots",
                        to="rfi.rfi",
                    ),
                ),
                (
                    "bim_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotspots",
                        to="bim.bimprojectmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "BIM Hotspot",
                "db_table": "bim_hotspots",
            },
        ),
    ]
