# Generated by Django 6.0.2 on 2026-03-13 18:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailylog",
            name="log_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-90.0")),
                    django.core.validators.MaxValueValidator(Decimal("90.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="lon",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-180.0")),
                    django.core.validators.MaxValueValidator(Decimal("180.0")),
                ],
            ),
        ),
    ]
