# Generated by Django 6.0.2 on 2026-04-12 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0003_alter_dailylog_log_date_alter_photo_created_at_and_more"),
        ("projects", "0021_add_is_frozen_to_projectmember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField(db_index=True)),
                ("weather", models.CharField(blank=True, default="", max_length=50)),
                ("crew_count", models.PositiveIntegerField(default=0)),
                (
                    "budget_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget consumed this week",
                        max_digits=12,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Summary of the week's accomplishments and blockers.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "pdf_s3_key",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attached_photos",
                    models.ManyToManyField(
                        blank=True, related_name="weekly_logs", to="photos.photo"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_logs",
                        to="projects.project",
                    ),
                ),
                (
                    "site_officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "weekly_logs",
                "ordering": ["-week_start_date"],
                "unique_together": {("project", "site_officer", "week_start_date")},
            },
        ),
        migrations.DeleteModel(
            name="DailyLog",
        ),
    ]
