# Generated by Django 6.0.2 on 2026-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CLIENT", "Client"),
                    ("AGENT", "Agent"),
                    ("SITE_OFFICER", "Site Officer"),
                    ("ADMIN", "Admin"),
                ],
                db_index=True,
                default="CLIENT",
                max_length=20,
            ),
        ),
    ]
